#version has been deprecated 
#https://docs.docker.com/compose/compose-file/#compose-file
#version: '3.8'

services:
  node:
    #node container will NOT run until mysql container has been started
      #it is possible to set more granular condition with long syntax = https://docs.docker.com/compose/compose-file/#long-syntax-1 
    platform: linux/amd64
    build: ./src
    env_file: 
      - ./.env
    ports:
      - $APP_PORT:$APP_PORT
    #stdin_open & tty together opens container in interactive mode = https://stackoverflow.com/questions/36249744/interactive-shell-using-docker-compose
      #stdin_open (i.e., docker run -i)= https://docs.docker.com/compose/compose-file/#stdin_open
    stdin_open: true
      #tty (i.e., docker run -t) = https://docs.docker.com/compose/compose-file/#tty
    tty: true

